series: GLFW Graphics
title: Improved 3D
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program serves to demonstrate what a basic 3D OpenGL program looks like and builds off of the Standard 3D tutorial.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Standard 3D
